# Generated by Django 6.0.2 on 2026-02-25 14:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('add_venue', 'Add New Venue'), ('edit_venue', 'Edit Venue'), ('add_field_value', 'Add Field Value'), ('edit_field_value', 'Edit Field Value')], max_length=20, verbose_name='Contribution Type')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('moderation_note', models.TextField(blank=True, verbose_name='Moderation Note')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Moderated At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='accounts.userprofile', verbose_name='Contributor')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_contributions', to='accounts.userprofile', verbose_name='Moderator')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='venues.venue', verbose_name='Venue')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalContribution',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('add_venue', 'Add New Venue'), ('edit_venue', 'Edit Venue'), ('add_field_value', 'Add Field Value'), ('edit_field_value', 'Edit Field Value')], max_length=20, verbose_name='Contribution Type')),
                ('payload', models.JSONField(verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('moderation_note', models.TextField(blank=True, verbose_name='Moderation Note')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Moderated At')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contributor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.userprofile', verbose_name='Contributor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.userprofile', verbose_name='Moderator')),
                ('venue', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='venues.venue', verbose_name='Venue')),
            ],
            options={
                'verbose_name': 'historical Contribution',
                'verbose_name_plural': 'historical Contributions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VenueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('closed', 'Venue Closed / Not Found'), ('wrong_location', 'Wrong Location on Map'), ('wrong_info', 'Incorrect Information'), ('inappropriate', 'Inappropriate Content'), ('duplicate', 'Duplicate Entry'), ('other', 'Other')], max_length=50, verbose_name='Reason')),
                ('description', models.TextField(blank=True, verbose_name='Additional Details')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.userprofile', verbose_name='Reporter')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='venues.venue', verbose_name='Venue')),
            ],
            options={
                'verbose_name': 'Venue Report',
                'verbose_name_plural': 'Venue Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
