# Generated by Django 6.0.2 on 2026-02-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='contribution_type',
            field=models.CharField(choices=[('add_venue', 'Add New Venue'), ('edit_venue', 'Edit Venue'), ('add_field_value', 'Add Field Value'), ('edit_field_value', 'Edit Field Value'), ('add_category', 'Add Category to Venue')], max_length=20, verbose_name='Contribution Type'),
        ),
        migrations.AlterField(
            model_name='historicalcontribution',
            name='contribution_type',
            field=models.CharField(choices=[('add_venue', 'Add New Venue'), ('edit_venue', 'Edit Venue'), ('add_field_value', 'Add Field Value'), ('edit_field_value', 'Edit Field Value'), ('add_category', 'Add Category to Venue')], max_length=20, verbose_name='Contribution Type'),
        ),
    ]
