# Generated by Django 6.0.2 on 2026-02-25 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Field Name')),
                ('label', models.CharField(max_length=255, verbose_name='Display Label')),
                ('field_type', models.CharField(choices=[('boolean', 'Boolean (Yes/No)'), ('string', 'Short Text'), ('text', 'Long Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('url', 'URL')], max_length=20, verbose_name='Field Type')),
                ('is_required', models.BooleanField(default=False, verbose_name='Required')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('help_text', models.CharField(blank=True, max_length=500, verbose_name='Help Text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='categories.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Field Definition',
                'verbose_name_plural': 'Field Definitions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='categories.fielddefinition', verbose_name='Field')),
            ],
            options={
                'verbose_name': 'Field Value',
                'verbose_name_plural': 'Field Values',
            },
        ),
    ]
