# Generated by Django 6.0.2 on 2026-02-25 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalue',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='venues.venue', verbose_name='Venue'),
        ),
        migrations.AlterUniqueTogether(
            name='fielddefinition',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='fieldvalue',
            unique_together={('venue', 'field')},
        ),
    ]
