# Generated by Django 6.0.2 on 2026-02-25 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_categories', to=settings.AUTH_USER_MODEL, verbose_name='Moderators'),
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_categories', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
