# Generated by Django 6.0.2 on 2026-02-26 12:08
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('venues', '0001_initial'),
    ]
    operations = [
        migrations.AlterField(
            model_name='historicalvenue',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
