# Generated by Django 6.0.2 on 2026-02-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_alter_historicalvenue_slug_alter_venue_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvenue',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Map URL'),
        ),
        migrations.AddField(
            model_name='venue',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Map URL'),
        ),
    ]
