# Generated by Django 6.0.2 on 2026-02-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venuecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvenue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalvenue',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalvenue',
            name='map_url',
        ),
        migrations.AlterField(
            model_name='venuecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
